// Generated by tools/stage_living_preview.py; edit the authoring JSON.
#pragma once
#include <array>
#include <dh/sim/effects.hpp>
#include <dh/content/lairs.generated.hpp>
namespace dh::sim::living_data {
inline constexpr unsigned simulation_stamp = 2429298649u;
using Phase = dh::content::lairs::Phase;
inline constexpr std::array<EffectDef,4> effects = {{
{EffectTrigger::hit,1,1,1,EffectAction::chain,250,90,3,24},
{EffectTrigger::dodge,4,0,0,EffectAction::resource,150,90,1,12},
{EffectTrigger::hit,2,0,0,EffectAction::echo,350,45,1,18},
{EffectTrigger::pet_hit,8,0,0,EffectAction::ward,250,150,1,20},
}};
inline constexpr std::array<unsigned,4> visual_ticks = {17,17,17,17};
inline constexpr std::array<unsigned,4> artifact_masks = {4,6,7,15};
inline constexpr std::array<float,4> affixes = {82.0f,70.0f,46.0f,26.0f};
inline constexpr auto phases = dh::content::lairs::definitions[0].phases;
inline constexpr float boss_hp = dh::content::lairs::definitions[0].boss_hp;
inline constexpr float hunter_hp = 140.000000f;
inline constexpr float move_speed = 135.000000f;
inline constexpr float base_damage = 30.000000f;
inline constexpr float affix_damage_per_point = 0.120000f;
} // namespace dh::sim::living_data
