// Generated by tools/stage_living_preview.py; edit authoring JSON.
#pragma once
#include <array>
#include <string_view>
namespace dh::content::lairs {
struct Phase { unsigned verb, windup, recovery; float damage, radius; };
struct Definition { std::string_view id, creature; unsigned salt, region_chunks; float boss_hp; unsigned phase_count; std::array<Phase,8> phases; unsigned reward_count; std::array<unsigned,16> rewards; };
inline constexpr unsigned placement_version=1;
inline constexpr std::array<Definition,1> definitions = {{
{"fen_bells.lair.bell_shrine","fen_bells.creature.orun",72413,3,1400.000000f,5,{{
{0,30,65,8.000000f,34.000000f},
{1,36,45,24.000000f,45.000000f},
{2,24,40,18.000000f,38.000000f},
{3,24,65,18.000000f,68.000000f},
{4,45,80,20.000000f,78.000000f},
}},4,{0,1,2,3}},
}};
inline constexpr std::array<std::string_view,4> artifact_ids = {"fen_bells.item.widows_refrain","fen_bells.item.pilgrim_bell","fen_bells.item.storm_canticle","fen_bells.item.crown_of_return"};
inline constexpr float rush_hp_step = 0.100000f;
inline constexpr float rush_hp_cap = 1.500000f;
inline constexpr float rush_rest_heal_fraction = 0.350000f;
} // namespace dh::content::lairs
