# Local portable llvm-mingw; override DH_MINGW_ROOT for another installation.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(DH_MINGW_ROOT "$ENV{DH_MINGW_ROOT}")
if(NOT DH_MINGW_ROOT)
    set(DH_MINGW_ROOT "$ENV{HOME}/.local/share/dh-toolchains/llvm-mingw-20260908-ucrt-ubuntu-22.04-x86_64")
endif()
set(CMAKE_C_COMPILER "${DH_MINGW_ROOT}/bin/x86_64-w64-mingw32-clang")
set(CMAKE_CXX_COMPILER "${DH_MINGW_ROOT}/bin/x86_64-w64-mingw32-clang++")
set(CMAKE_RC_COMPILER "${DH_MINGW_ROOT}/bin/x86_64-w64-mingw32-windres")
set(CMAKE_FIND_ROOT_PATH "${DH_MINGW_ROOT}/x86_64-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
# Package a standalone helper without llvm-mingw runtime DLL dependencies.
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static")
