# ARENA tool — dump every build's REAL combat stats to JSON for dh-env
# (docs/tech/25): the C++ arena gets its numbers from the actual Godot bodies,
# never a hand-copied table, so balance changes reach training automatically.
#
#   godot --headless --path game -s res://arena/tools/dump_specs.gd \
#       -- --out <abs path to ml/env/specs.json>
extends Node

const ProtoPlayerScript := preload("res://prototype/player.gd")

const ArenaFighterScript := preload("res://arena/fighter.gd")
const ArenaBuildsScript := preload("res://arena/builds.gd")

func _ready() -> void:
	var out := ""
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--out="):
			out = a.trim_prefix("--out=")
	if out == "":
		push_error("dump_specs: pass --out=<abs path>")
		get_tree().quit(1)
		return
	var catalog: Dictionary = ArenaBuildsScript.catalog()
	var stub := Node2D.new()   # fighter.setup only needs add_child + groups
	add_child(stub)
	var specs := {}
	for build_id in catalog.get("builds", {}).keys():
		var def: Dictionary = ArenaBuildsScript.build_def(build_id)
		if def.is_empty() or str(def.get("kind", "")) == "duo":
			continue   # duos join dh-env with multi-fighter arenas (roadmap)
		var f: ArenaFighter = ArenaFighterScript.new()
		f.setup(def, stub, Vector2.ZERO, "native", 1)
		var b := f.alive_body()
		var spec := {"kind": str(def.get("kind", "creature"))}
		if b is ProtoPlayer:
			spec.max_hp = b.max_hp
			spec.damage = b.attack_damage
			spec.move_speed = b.move_speed
			spec.attack_reach = b.attack_reach
			spec.attack_cd = b.attack_cd_s
			spec.body_radius = b.body_radius
			spec.special_cd = b.whirl_cd_s
			spec.dodge_max = ProtoPlayer.DODGE_CHARGES_MAX
			spec.is_player = true
			spec.is_ranged = str(b._kit) == "mage"
		else:
			spec.max_hp = b.max_hp
			spec.damage = b.damage
			spec.move_speed = b._speed()
			spec.attack_reach = b.attack_reach
			spec.attack_cd = b.attack_cd
			spec.body_radius = b.body_radius
			spec.special_cd = 6.0
			spec.dodge_max = 0
			spec.is_player = false
			spec.is_ranged = b is ProtoWisp
		var kits: Array = []
		for k in def.get("skills", []):
			kits.append({"id": str(k.get("id", "")), "cd": float(k.get("cd", 6.0)),
					"range": float(k.get("range", 112.0)),
					"kind": str(k.get("kind", "fire"))})
		spec.kits = kits
		specs[build_id] = spec
		f.free_body()
	var FIELD_KINDS := {"fire": 0, "earth": 1, "mire": 2, "lava": 3}
	var doc := {"schema": "arena.specs.v1",
			"note": "GENERATED by game/arena/tools/dump_specs.gd — do not hand-edit",
			"field_kind_ids": FIELD_KINDS,
			"builds": specs}
	var file := FileAccess.open(out, FileAccess.WRITE)
	if file == null:
		push_error("dump_specs: cannot write " + out)
		get_tree().quit(1)
		return
	file.store_string(JSON.stringify(doc, "  "))
	file.close()
	print("dump_specs: %d builds -> %s" % [specs.size(), out])
	get_tree().quit(0)
