# PROTOTYPE HARNESS — chrome localization (EN / PT-BR). Static-only API, no
# autoload: ProtoLang.t("key") for fixed chrome strings, ProtoLang.pick(dict,
# "field") for data-driven text (skill_trees.json carries name_pt/desc_pt/
# synergy_pt next to the EN fields). The language persists in
# user://settings.json and defaults to "en" (tests run in English). Proper
# nouns — item names, creature names, class names like Veilblade — stay
# untranslated by design; only the words AROUND them localize. The shipping
# localization pipeline is a real .po/CSV pass through dh-content later.
class_name ProtoLang
extends RefCounted

const SETTINGS_PATH := "user://settings.json"

static var lang := "en"
static var _loaded := false

# key -> {en, pt}. EN values are the exact strings the prototype shipped with
# (the click test asserts several of them verbatim).
const S := {
	"hud_summary": {"en": "Lv %d · %d gold · Bag %d/%d", "pt": "Nv %d · %d ouro · Bolsa %d/%d"},
	"mount_speed": {"en": "speed", "pt": "velocidade"},
	"mount_controls": {"en": "Z · Ride / dismount\nFlying · Cross obstacles\nCombat · Dismounts automatically", "pt": "Z · Montar / desmontar\nVoo · Atravessa obstáculos\nCombate · Desmonta automaticamente"},
	"companion_potential": {"en": "potential", "pt": "potencial"},
	"companion_skills": {"en": "skills", "pt": "habilidades"},
	"hud_flask": {"en": "EMBER FLASK", "pt": "FRASCO ÍGNEO"},
	"hud_flask_tip": {"en": "R · Heal 20% now + 20% over 2 seconds. Six kills restore a charge.", "pt": "R · Cura 20% agora + 20% em 2 segundos. Seis abates restauram uma carga."},

	"opt_visibility": {"en": "World visibility · moody / luminous", "pt": "Visibilidade · sombrio / luminoso"},
	"opt_visibility_hint": {"en": "Lift dark terrain and creatures while preserving spell highlights.", "pt": "Clareia terreno e criaturas sem apagar o brilho das magias."},
	"hv_main_menu": {"en": "MAIN MENU", "pt": "MENU PRINCIPAL"},
	"hv_stable_status": {"en": "Resting in Haven", "pt": "Descansando no Refúgio"},
	"companion_nickname": {"en": "Nickname", "pt": "Apelido"},
	"companion_rename": {"en": "Save", "pt": "Salvar"},
	# ---- shared ----------------------------------------------------------------
	"lang_toggle": {"en": "Language: EN", "pt": "Idioma: PT-BR"},
	"gold_line": {"en": "Gold: %d", "pt": "Ouro: %d"},
	"rarity_common": {"en": "common", "pt": "comum"},
	"rarity_uncommon": {"en": "uncommon", "pt": "incomum"},
	"rarity_rare": {"en": "rare", "pt": "raro"},
	"rarity_epic": {"en": "epic", "pt": "épico"},
	"rarity_legendary": {"en": "legendary", "pt": "lendário"},
	"slot_weapon": {"en": "Weapon", "pt": "Arma"},
	"slot_chest": {"en": "Chest", "pt": "Peitoral"},
	"slot_helm": {"en": "Helm", "pt": "Elmo"},
	"slot_boots": {"en": "Boots", "pt": "Botas"},
	"slot_amulet": {"en": "Amulet", "pt": "Amuleto"},
	"slot_ring": {"en": "Ring", "pt": "Anel"},
	"slot_rune": {"en": "Rune", "pt": "Runa"},
	"slot_material": {"en": "Material", "pt": "Material"},
	"where_equipped": {"en": "equipped", "pt": "equipado"},
	"where_bag": {"en": "bag", "pt": "bolsa"},
	"dt_physical": {"en": "physical", "pt": "físico"},
	"dt_umbral": {"en": "umbral", "pt": "umbral"},
	"dt_fire": {"en": "fire", "pt": "fogo"},
	"dt_frost": {"en": "frost", "pt": "gelo"},
	"dt_earth": {"en": "earth", "pt": "terra"},
	"dt_arcane": {"en": "arcane", "pt": "arcano"},

	# ---- main menu ---------------------------------------------------------------
	"menu_subtitle": {"en": "BENEATH THE GLOOM, A LEGEND WAKES", "pt": "SOB O GLOOM, UMA LENDA DESPERTA"},
	"menu_hunter_name": {"en": "hunter name", "pt": "nome do caçador"},
	"menu_password": {"en": "password", "pt": "senha"},
	"menu_enter": {"en": "Enter the World", "pt": "Entrar no Mundo"},
	"menu_saved": {"en": "saved hunters: %s — enter a name to continue",
			"pt": "caçadores salvos: %s — digite um nome para continuar"},
	"menu_foot": {"en": "Name your hunter, or Quick Start to continue your journey.",
			"pt": "Dê um nome ao caçador ou use JOGO RÁPIDO para continuar."},
	"menu_options": {"en": "OPTIONS", "pt": "OPÇÕES"},
	"menu_quick": {"en": "QUICK START — %s", "pt": "JOGO RÁPIDO — %s"},
	"opt_music": {"en": "Music", "pt": "Música"},
	"opt_sfx": {"en": "Effects", "pt": "Efeitos"},
	"opt_mode": {"en": "Mode", "pt": "Modo"},
	"opt_fit": {"en": "Fit", "pt": "Escala"},
	"opt_back": {"en": "BACK", "pt": "VOLTAR"},
	"msg_flask_sip": {"en": "HP restored — healing continues for 2 seconds",
			"pt": "Vida restaurada — a cura continua por 2 segundos"},
	"msg_flask_healing": {"en": "the Flask is still healing you", "pt": "o Frasco ainda está curando você"},
	"msg_flask_full": {"en": "HP is full — charge saved", "pt": "Vida cheia — carga preservada"},
	"msg_flask_dead": {"en": "return to life before drinking", "pt": "volte à vida antes de beber"},
	"msg_flask_empty": {"en": "the flask is empty — 6 kills rekindle a charge",
			"pt": "o frasco está vazio — 6 abates reacendem uma carga"},
	"msg_flask_charge": {"en": "an ember charge rekindles",
			"pt": "uma carga de brasa se reacende"},

	# ---- Haven: chrome -------------------------------------------------------------
	"hv_welcome_title": {"en": "Haven — welcome, %s", "pt": "Refúgio — bem-vindo, %s"},
	"hv_stats": {"en": "Level %d · Gold %d · Kills %d · Points %d · Stones %d · Snares %d · Pets %d/%d · Bag %d/%d · Weapon: %s",
			"pt": "Nível %d · Ouro %d · Abates %d · Pontos %d · Pedras %d · Laços %d · Pets %d/%d · Bolsa %d/%d · Arma: %s"},
	"hv_unarmed": {"en": "unarmed", "pt": "desarmado"},
	"hv_go_hunting": {"en": "GO HUNTING", "pt": "CAÇAR"},
	"hv_character": {"en": "CHARACTER", "pt": "PERSONAGEM"},
	"hv_skills": {"en": "SKILLS", "pt": "HABILIDADES"},
	"hv_pets": {"en": "PETS", "pt": "PETS"},
	"hv_attributes": {"en": "ATTRIBUTES", "pt": "ATRIBUTOS"},
	"hv_forge": {"en": "FORGE", "pt": "FORJA"},
	"hv_enchanter": {"en": "ENCHANTER", "pt": "ENCANTADOR"},
	"hv_vendor": {"en": "VENDOR", "pt": "VENDEDOR"},
	"hv_chest": {"en": "CHEST", "pt": "BAÚ"},
	"hv_codex": {"en": "CODEX", "pt": "CÓDICE"},
	"hv_quit": {"en": "QUIT", "pt": "SAIR"},
	"hv_title": {"en": "Haven", "pt": "Refúgio"},
	"hv_welcome_line": {"en": "The hunt waits beyond the gloam.",
			"pt": "A caçada espera além da penumbra."},
	"hv_welcome_body": {"en": "Gear up (CHARACTER: equip loot, spend attribute points, socket runes), then improve your kit at the FORGE and the ENCHANTER, sell scraps at the VENDOR — and GO HUNTING. The Emberwing Matriarch nests in the far woods.",
			"pt": "Prepare-se (PERSONAGEM: equipe itens, gaste pontos de atributo, encaixe runas), depois melhore seu equipamento na FORJA e no ENCANTADOR, venda sobras no VENDEDOR — e vá CAÇAR. A Matriarca Emberwing aninha-se nas matas distantes."},

	# ---- Haven: skills kiosk ----------------------------------------------------------
	"hv_skills_title": {"en": "Skills — %s tree", "pt": "Habilidades — árvore de %s"},
	"hv_skills_summary": {"en": "Class: %s — %d actives + %d passives, requires-gated. %d learned, ",
			"pt": "Classe: %s — %d ativas + %d passivas, com pré-requisitos. %d aprendidas, "},
	"hv_skills_banked": {"en": "%d skill points banked (1 per level).",
			"pt": "%d pontos de habilidade guardados (1 por nível)."},
	"hv_skills_open_tree": {"en": "Open the visual tree in CHARACTER → Skills (C): click any node for live numbers, learn it, and assign actives to keys 1-4. Synergies are on the cards: Bleed, Ignite, Chill, Expose, Stagger.",
			"pt": "Abra a árvore visual em PERSONAGEM → Habilidades (C): clique em qualquer nó para ver números ao vivo, aprendê-lo e atribuir ativas às teclas 1-4. As sinergias estão nos cartões: Sangramento, Ignição, Gelidez, Exposição, Atordoamento."},
	"hv_cleave_header": {"en": "Cleave (%s)", "pt": "Cutilada (%s)"},
	"hv_cleave_stats": {"en": "coeff x%.1f  ·  reach %.1f m  ·  arc %d deg  ·  cooldown %d s  ·  %s damage",
			"pt": "coef. x%.1f  ·  alcance %.1f m  ·  arco %d°  ·  recarga %d s  ·  dano %s"},
	"hv_runes_header": {"en": "Runes (canon §4 — socket one per skill)",
			"pt": "Runas (cânone §4 — encaixe uma por habilidade)"},
	"hv_runes_drop": {"en": "Runes drop from Elites (the first Elite kill guarantees one). Socket them in CHARACTER → Skills; the effects are LIVE in combat.",
			"pt": "Runas caem de Elites (o primeiro abate de Elite garante uma). Encaixe-as em PERSONAGEM → Habilidades; os efeitos ficam ATIVOS em combate."},

	# ---- Haven: pets kiosk ---------------------------------------------------------
	"hv_pets_title": {"en": "Pets — Abyssal family (%d/%d bonded)",
			"pt": "Pets — família Abissal (%d/%d vinculados)"},
	"hv_pets_none": {"en": "No pet bonded yet — on the hunt, wound a Gloamfen Stalker below 35% HP and press F with a Soul Snare (stalkers drop them).",
			"pt": "Nenhum pet vinculado ainda — na caçada, fira um Gloamfen Stalker abaixo de 35% de HP e aperte F com um Laço de Alma (os stalkers os derrubam)."},
	"hv_pets_roll": {"en": "attribute roll %d%%  ·  %s", "pt": "rolagem de atributos %d%%  ·  %s"},
	"hv_stables_header": {"en": "Stables (%d) — pets are never abandoned",
			"pt": "Estábulo (%d) — pets nunca são abandonados"},
	"hv_stables_row": {"en": "- %s  ·  roll %d%%  ·  %d skills",
			"pt": "- %s  ·  rolagem %d%%  ·  %d habilidades"},
	"hv_stables_manage": {"en": "Swap active/stabled pets in CHARACTER → Pets.",
			"pt": "Troque pets ativos/estabulados em PERSONAGEM → Pets."},
	"hv_pets_rules": {"en": "All bonded pets join every hunt and fight together (3 active slots, proposal). Capturing with full slots asks for an F-again confirm and STABLES the oldest bond. Pets rest 15 s when their HP empties and reset with you on death — they never die.",
			"pt": "Todos os pets vinculados entram em cada caçada e lutam juntos (3 slots ativos, proposta). Capturar com os slots cheios pede um F de confirmação e ESTABULA o vínculo mais antigo. Pets descansam 15 s quando o HP esvazia e renascem com você na morte — eles nunca morrem."},
	"hv_family_skills": {"en": "Family-shared skills", "pt": "Habilidades da família"},
	"hv_species": {"en": "Species", "pt": "Espécies"},
	"hv_species_row": {"en": "- %s — signature: %s", "pt": "- %s — assinatura: %s"},
	"hv_roll_rules": {"en": "Roll rules: %d skill slots  ·  %d%% family-skill chance  ·  attribute rolls %d-%d%%",
			"pt": "Regras de rolagem: %d slots de habilidade  ·  %d%% de chance de habilidade da família  ·  rolagens de atributo %d-%d%%"},

	# ---- Haven: attributes kiosk ------------------------------------------------------
	"hv_attr_title": {"en": "Attributes — allocation is REAL",
			"pt": "Atributos — a alocação é REAL"},
	"unspent_points": {"en": "Unspent points: %d", "pt": "Pontos não gastos: %d"},
	"attr_might": {"en": "Might", "pt": "Força"},
	"attr_agility": {"en": "Agility", "pt": "Agilidade"},
	"attr_intellect": {"en": "Intellect", "pt": "Intelecto"},
	"attr_vitality": {"en": "Vitality", "pt": "Vitalidade"},
	"attr_willpower": {"en": "Willpower", "pt": "Vontade"},
	"fx_might": {"en": "+2% melee damage/pt", "pt": "+2% dano corpo a corpo/pt"},
	"fx_agility": {"en": "+1% move · +2% dodge recharge/pt",
			"pt": "+1% movimento · +2% recarga de esquiva/pt"},
	"fx_intellect": {"en": "+2% skill damage/pt", "pt": "+2% dano de habilidade/pt"},
	"fx_vitality": {"en": "+6 max HP/pt", "pt": "+6 HP máximo/pt"},
	"fx_willpower": {"en": "+1% resist · +2% status resist/pt",
			"pt": "+1% resistência · +2% resist. a status/pt"},
	# short variants for the 312 px character panel rows
	"fxs_might": {"en": "+2% melee dmg", "pt": "+2% dano c.c."},
	"fxs_agility": {"en": "+1% move, +2% dodge rchg", "pt": "+1% mov, +2% rec. esq."},
	"fxs_intellect": {"en": "+2% skill dmg", "pt": "+2% dano hab."},
	"fxs_vitality": {"en": "+6 max HP", "pt": "+6 HP máx."},
	"fxs_willpower": {"en": "+1% resist, +2% status res", "pt": "+1% resist, +2% res. status"},
	"hv_attr_note": {"en": "Effects (stats.gd, proposals) apply at hunt start and re-apply live mid-hunt from the character panel. +5 points per level — every 20 kills.",
			"pt": "Os efeitos (stats.gd, propostas) aplicam-se no início da caçada e reaplicam ao vivo no meio dela pelo painel do personagem. +5 pontos por nível — a cada 20 abates."},

	# ---- Haven: forge -------------------------------------------------------------------
	"hv_forge_title": {"en": "Forge — upgrade gear", "pt": "Forja — aprimorar equipamento"},
	"hv_forge_none": {"en": "no gear yet — hunt for drops.",
			"pt": "sem equipamento ainda — cace por espólios."},
	"hv_forge_pick_hint": {"en": "pick a piece of gear below to preview its next tier.",
			"pt": "escolha uma peça abaixo para prever o próximo nível."},
	"hv_forge_before_after": {"en": "%s — before → after", "pt": "%s — antes → depois"},
	"hv_forge_max": {"en": "already at max tier (+%d).", "pt": "já está no nível máximo (+%d)."},
	"hv_forge_affix_row": {"en": "%s: +%.0f → +%.0f", "pt": "%s: +%.0f → +%.0f"},
	"hv_forge_enchant_note": {"en": "enchant +%.0f %s (does not scale with tiers)",
			"pt": "encantamento +%.0f %s (não escala com os níveis)"},
	"hv_forge_upgrade_btn": {"en": "UPGRADE to +%d — %d gold%s",
			"pt": "APRIMORAR para +%d — %d de ouro%s"},
	"hv_fail_risk": {"en": "  ·  FAIL RISK %d%%", "pt": "  ·  RISCO DE FALHA %d%%"},
	"hv_no_gold": {"en": "not enough gold.", "pt": "ouro insuficiente."},
	"hv_forge_pick_section": {"en": "pick gear — equipped first, then bag",
			"pt": "escolha o equipamento — equipados primeiro, depois a bolsa"},
	"hv_forge_rules": {"en": "+10% to ALL affix values per tier, max +5. Cost 50 x 2^tier gold. Attempts into +4/+5 FAIL 25%/40% — the gold burns, the item survives.",
			"pt": "+10% em TODOS os valores de afixo por nível, máx. +5. Custo 50 x 2^nível de ouro. Tentativas para +4/+5 FALHAM 25%/40% — o ouro queima, o item sobrevive."},
	"hv_gear_row": {"en": "%s%s · pw %d · tier +%d (%s)", "pt": "%s%s · pd %d · nível +%d (%s)"},
	"hv_forged_msg": {"en": "forged: %s — affixes +10%%.", "pt": "forjado: %s — afixos +10%%."},
	"hv_forge_failed": {"en": "the forge FAILED — %d gold burned; the item survives.",
			"pt": "a forja FALHOU — %d de ouro queimado; o item sobrevive."},

	# ---- Haven: enchanter ----------------------------------------------------------------
	"hv_ench_title": {"en": "Enchanter — Spirit Essences", "pt": "Encantador — Essências Espirituais"},
	"hv_ench_count": {"en": "Essences in bag: %d  (Abyssal Remnants drop from abyssal kills — 8%%)",
			"pt": "Essências na bolsa: %d  (Resquícios Abissais caem de abates abissais — 8%%)"},
	"hv_ench_none": {"en": "no essences — hunt Gloamfen Stalkers.",
			"pt": "sem essências — cace Gloamfen Stalkers."},
	"hv_ench_pick_hint": {"en": "pick a weapon or amulet below to enchant.",
			"pt": "escolha uma arma ou amuleto abaixo para encantar."},
	"hv_ench_current": {"en": "current enchant: +%.0f %s — a new essence REPLACES it",
			"pt": "encantamento atual: +%.0f %s — uma nova essência o SUBSTITUI"},
	"hv_ench_none_yet": {"en": "no enchant yet.", "pt": "sem encantamento ainda."},
	"hv_ench_apply": {"en": "APPLY ESSENCE (+4-10% umbral)", "pt": "APLICAR ESSÊNCIA (+4-10% umbral)"},
	"hv_ench_pick_section": {"en": "pick gear — weapons and amulets",
			"pt": "escolha o equipamento — armas e amuletos"},
	"hv_ench_rules": {"en": "Apply an Abyssal Remnant to a weapon or amulet: adds or REPLACES its enchant with +4-10% umbral damage (rolled). The essence is the only cost — enchanting never destroys gear.",
			"pt": "Aplique um Resquício Abissal a uma arma ou amuleto: adiciona ou SUBSTITUI o encantamento por +4-10% de dano umbral (rolado). A essência é o único custo — encantar nunca destrói o equipamento."},
	"hv_ench_row": {"en": "%s%s · tier +%d (%s)", "pt": "%s%s · nível +%d (%s)"},
	"hv_ench_no_gear": {"en": "no enchantable gear (weapon/amulet) owned.",
			"pt": "nenhum equipamento encantável (arma/amuleto)."},
	"hv_ench_done": {"en": "enchanted %s: +%d %s.", "pt": "%s encantado: +%d %s."},

	# ---- Haven: vendor --------------------------------------------------------------------
	"hv_vendor_title": {"en": "Vendor — sell loot", "pt": "Vendedor — vender espólios"},
	"hv_bag_empty": {"en": "the bag is empty.", "pt": "a bolsa está vazia."},
	"hv_sell_all_chip": {"en": "all %s (%d) — %dg", "pt": "todo %s (%d) — %dg"},
	"hv_sell_row": {"en": "sell %s%s — %d gold", "pt": "vender %s%s — %d de ouro"},
	"hv_stable_master": {"en": "stable-master — mounts (proposal)",
			"pt": "mestre do estábulo — montarias (proposta)"},
	"hv_strider_owned": {"en": "Gloam Strider owned — manage mounts in CHARACTER → Mounts; ride with M.",
			"pt": "Gloam Strider adquirido — gerencie montarias em PERSONAGEM → Montarias; monte com Z."},
	"hv_buy_strider": {"en": "buy GLOAM STRIDER — walking mount, x1.6 speed — 400 gold",
			"pt": "comprar GLOAM STRIDER — montaria terrestre, x1,6 de velocidade — 400 de ouro"},
	"hv_no_fly_sale": {"en": "a FLYING mount is not for sale — the Matriarch's brood bonds only with whoever fells her.",
			"pt": "montaria VOADORA não está à venda — a ninhada da Matriarca só se vincula a quem a derruba."},
	"hv_market_note": {"en": "Prices scale with rarity and forge tier (proposal). Player-to-player trade is the WEB-ONLY marketplace later (docs/design/15) — never in the mobile apps.",
			"pt": "Os preços escalam com raridade e nível de forja (proposta). O comércio entre jogadores é o mercado SÓ NA WEB depois (docs/design/15) — nunca nos aplicativos móveis."},
	"hv_strider_bought": {"en": "the Gloam Strider is yours — press Z on the hunt to ride.",
			"pt": "o Gloam Strider é seu — aperte Z na caçada para montar."},
	"hv_sold_n": {"en": "sold %d items for %d gold.", "pt": "%d itens vendidos por %d de ouro."},
	"hv_sold_one": {"en": "sold %s for %d gold.", "pt": "%s vendido por %d de ouro."},

	# ---- Haven: chest ----------------------------------------------------------------------
	"hv_chest_title": {"en": "Chest — %d/%d stored  ·  bag %d/%d",
			"pt": "Baú — %d/%d guardados  ·  bolsa %d/%d"},
	"hv_chest_note": {"en": "Store loot between hunts — enchants, tiers and stacks travel whole. The chest lives at the Haven (proposal).",
			"pt": "Guarde espólios entre caçadas — encantamentos, níveis e pilhas viajam inteiros. O baú fica no Refúgio (proposta)."},
	"hv_chest_store_sec": {"en": "bag → store (%d)", "pt": "bolsa → guardar (%d)"},
	"hv_chest_take_sec": {"en": "chest → take (%d)", "pt": "baú → pegar (%d)"},
	"hv_chest_empty": {"en": "the chest is empty.", "pt": "o baú está vazio."},
	"hv_chest_store_row": {"en": "store %s%s", "pt": "guardar %s%s"},
	"hv_chest_take_row": {"en": "take %s%s", "pt": "pegar %s%s"},

	# ---- Haven: codex ----------------------------------------------------------------------
	"hv_codex_title": {"en": "Codex — every effect in the game",
			"pt": "Códice — todos os efeitos do jogo"},
	"hv_codex_note": {"en": "Statuses, conditions, mechanics, enchantments, affixes and fields — one expandable registry (prototype/data/effects.json ← content/core/registries/effects.json). [planned] = designed, not yet in the slice.",
			"pt": "Status, condições, mecânicas, encantamentos, afixos e campos — um registro expansível (prototype/data/effects.json ← content/core/registries/effects.json). [planejado] = projetado, ainda fora da fatia."},
	"hv_codex_planned": {"en": "  [planned]", "pt": "  [planejado]"},

	# ---- character panel: shell / gear / bag ----------------------------------------------
	"cp_title": {"en": "CHARACTER", "pt": "PERSONAGEM"},
	"cp_close_hint": {"en": "Esc / C close", "pt": "Esc / C fechar"},
	"tab_gear": {"en": "Gear", "pt": "Equip."},
	"tab_bag": {"en": "Bag", "pt": "Bolsa"},
	"tab_attributes": {"en": "Attributes", "pt": "Atrib."},
	"tab_skills": {"en": "Skills", "pt": "Habilid."},   # full word overflows the 296 px tab bar
	"tab_pets": {"en": "Pets", "pt": "Pets"},
	"tab_mounts": {"en": "Mounts", "pt": "Mont."},
	"cp_gear_header": {"en": "%s — %s, level %d", "pt": "%s — %s, nível %d"},
	"cp_slot_empty": {"en": "%s — empty", "pt": "%s — vazio"},
	"cp_slot_row": {"en": "%s — %s · pw %d", "pt": "%s — %s · pd %d"},
	"cp_item_meta": {"en": "%s %s · sells %d gold", "pt": "%s %s · vende por %d de ouro"},
	"cp_unequip": {"en": "Unequip", "pt": "Desequipar"},
	"cp_bag_full": {"en": "bag full — sell something first",
			"pt": "bolsa cheia — venda algo primeiro"},
	"cp_bag_header": {"en": "Bag %d/%d — gold %d", "pt": "Bolsa %d/%d — ouro %d"},
	"cp_bag_empty": {"en": "empty — creatures drop gear, essences and (from Elites) runes.",
			"pt": "vazia — criaturas derrubam equipamento, essências e (de Elites) runas."},
	"flt_all": {"en": "All", "pt": "Tudo"},
	"flt_gear": {"en": "Gear", "pt": "Equip."},
	"flt_runes": {"en": "Runes", "pt": "Runas"},
	"flt_mats": {"en": "Mats", "pt": "Mat."},
	"srt_rarity": {"en": "rarity", "pt": "raridade"},
	"srt_power": {"en": "power", "pt": "poder"},
	"srt_slot": {"en": "slot", "pt": "slot"},
	"cp_sort_tip": {"en": "sort the bag by %s", "pt": "ordenar a bolsa por %s"},
	"cp_rarity_slot": {"en": "%s %s", "pt": "%s %s"},
	"cp_selected": {"en": "SELECTED", "pt": "SELECIONADO"},
	"cp_equipped": {"en": "EQUIPPED", "pt": "EQUIPADO"},
	"cp_pw": {"en": "%s · pw %d", "pt": "%s · pd %d"},
	"cmp_max_hp": {"en": "max HP", "pt": "HP máx."},
	"cmp_melee": {"en": "melee dmg", "pt": "dano c. a c."},
	"cmp_rend": {"en": "rend dmg", "pt": "dano de rasgo"},
	"cmp_crit": {"en": "crit %", "pt": "crít %"},
	"cmp_move": {"en": "move %", "pt": "mov %"},
	"cmp_armor": {"en": "armor", "pt": "armadura"},
	"cmp_resist": {"en": "resist %", "pt": "resist %"},
	"cp_vs_diff": {"en": "  %s %+.1f vs equipped", "pt": "  %s %+.1f vs equipado"},
	"cp_no_change": {"en": "  no stat change vs equipped",
			"pt": "  sem mudança de atributos vs equipado"},
	"cp_rune_hint": {"en": "socket it on a skill — Skills tab",
			"pt": "encaixe numa habilidade — aba Habilidades"},
	"cp_mat_hint": {"en": "spend it at the Haven ENCHANTER",
			"pt": "gaste no ENCANTADOR do Refúgio"},
	"cp_equip": {"en": "Equip", "pt": "Equipar"},
	"cp_sell": {"en": "Sell %d g", "pt": "Vender %d g"},

	# ---- character panel: attributes --------------------------------------------------------
	"cp_attr_header": {"en": "Attributes — unspent points: %d",
			"pt": "Atributos — pontos não gastos: %d"},
	"cp_attr_note": {"en": "Allocation is REAL (stats.gd): +5 points per level, 1 level per 20 kills (proposal). Prototype allows refunds down to base %d.",
			"pt": "A alocação é REAL (stats.gd): +5 pontos por nível, 1 nível a cada 20 abates (proposta). O protótipo permite reembolso até a base %d."},

	# ---- character panel: skills tab ---------------------------------------------------------
	"cp_skill_points": {"en": "SKILL POINTS  %d", "pt": "PONTOS DE HABILIDADE  %d"},
	"cp_pts_tip": {"en": "+1 point per level", "pt": "+1 ponto por nível"},
	"cp_class_tree": {"en": "%s tree · +1 pt / level", "pt": "árvore de %s · +1 pt/nível"},
	"cp_tree_legend": {"en": "◆ pulsing border = learnable NOW · dim + lock = gated. Click any node for live numbers; learned actives assign to keys 1-4.",
			"pt": "◆ borda pulsante = aprendível AGORA · apagado + cadeado = bloqueado. Clique em qualquer nó para números ao vivo; ativas aprendidas atribuem-se às teclas 1-4."},
	"cp_no_tree": {"en": "no class tree data.", "pt": "sem dados da árvore de classe."},
	"cp_free_root": {"en": "%s — free root", "pt": "%s — raiz gratuita"},
	"cp_learned": {"en": "learned", "pt": "aprendida"},
	"cp_learn_pt": {"en": "LEARN · %d pt", "pt": "APRENDER · %d pt"},
	"cp_pt": {"en": "%d pt", "pt": "%d pt"},
	"cp_level_req": {"en": "level %d", "pt": "nível %d"},
	"cp_needs": {"en": "needs %s", "pt": "requer %s"},
	"cp_slot_empty_tip": {"en": "empty — learn an active in the tree, then tap its %d chip",
			"pt": "vazio — aprenda uma ativa na árvore e toque no chip %d dela"},
	"cp_slot_cast_tip": {"en": "casts on key %d — click to clear the slot",
			"pt": "conjura na tecla %d — clique para limpar o slot"},
	"cp_detail_hint": {"en": "Click a tree node to inspect it — live damage from your current stats, synergies, and the Learn / slot 1-4 actions land here.",
			"pt": "Clique num nó da árvore para inspecioná-lo — dano ao vivo dos seus atributos atuais, sinergias e as ações Aprender / slots 1-4 aparecem aqui."},
	"kind_melee_arc": {"en": "melee arc", "pt": "arco corpo a corpo"},
	"kind_projectile": {"en": "projectile", "pt": "projétil"},
	"kind_nova": {"en": "nova", "pt": "nova"},
	"kind_cone": {"en": "cone", "pt": "cone"},
	"kind_dash_strike": {"en": "dash strike", "pt": "golpe de investida"},
	"kind_buff": {"en": "buff", "pt": "buff"},
	"kind_field": {"en": "field", "pt": "campo"},
	"kind_chain": {"en": "chain", "pt": "corrente"},
	"kind_passive": {"en": "passive", "pt": "passiva"},
	"kind_keystone": {"en": "keystone", "pt": "pedra angular"},
	"elem_ember": {"en": "ember", "pt": "brasa"},
	"elem_frost": {"en": "frost", "pt": "gelo"},
	"elem_arcane": {"en": "arcane", "pt": "arcano"},
	"elem_steel": {"en": "steel", "pt": "aço"},
	"elem_damage": {"en": "%s damage", "pt": "dano de %s"},
	"cp_applies": {"en": "applies %s", "pt": "aplica %s"},
	"cp_x_vs": {"en": "x%s vs %s", "pt": "x%s contra %s"},
	"cp_consumes": {"en": "consumes %s", "pt": "consome %s"},
	"cp_consumes_tip": {"en": "spends the status on hit", "pt": "gasta o status ao acertar"},
	"cp_bonus_tip": {"en": "bonus damage against %s prey",
			"pt": "dano extra contra presas %s"},
	"vs_bleeding": {"en": "Bleeding", "pt": "Sangrando"},
	"vs_ignited": {"en": "Ignited", "pt": "Incendiadas"},
	"vs_chilled": {"en": "Chilled", "pt": "Gélidas"},
	"vs_exposed": {"en": "Exposed", "pt": "Expostas"},
	"vs_staggered": {"en": "Staggered", "pt": "Atordoadas"},
	"cp_charge_spend": {"en": "◈ spends %s", "pt": "◈ gasta %s"},
	"cp_free_root_note": {"en": "free root — always learned",
			"pt": "raiz gratuita — sempre aprendida"},
	"cp_learn_btn": {"en": "LEARN — %d pt", "pt": "APRENDER — %d pt"},
	"cp_unlock_note": {"en": "unlocks at level %d — you are %d",
			"pt": "desbloqueia no nível %d — você está no %d"},
	"cp_no_points": {"en": "no skill points — +1 per level",
			"pt": "sem pontos de habilidade — +1 por nível"},
	"cp_slot_label": {"en": "slot:", "pt": "slot:"},
	"cp_assign_tip": {"en": "assign %s to slot %d", "pt": "atribuir %s ao slot %d"},
	"cp_on_key_tip": {"en": "on key %d — click to clear",
			"pt": "na tecla %d — clique para limpar"},
	"cp_learned_active": {"en": "learned — casts on the gold key",
			"pt": "aprendida — conjura na tecla dourada"},
	"cp_learned_passive": {"en": "learned — passive, always on",
			"pt": "aprendida — passiva, sempre ativa"},
	"cp_dmg": {"en": "~%d dmg", "pt": "~%d dano"},
	"cp_jumps": {"en": "%d jumps", "pt": "%d saltos"},
	"cp_deg": {"en": "%d deg", "pt": "%d°"},
	"cp_cd": {"en": "%.1f s cd", "pt": "%.1f s rec"},
	"cp_min_level": {"en": "min level %d · cost %d pt", "pt": "nível mín. %d · custo %d pt"},

	# ---- character panel: base kit -------------------------------------------------------------
	"cp_base_kit": {"en": "— BASE KIT · runes socket here —",
			"pt": "— KIT BASE · runas encaixam aqui —"},
	"kit_arcane_bolt": {"en": "Arcane Bolt  (LMB)", "pt": "Seta Arcana  (LMB)"},
	"kit_frost_nova": {"en": "Frost Nova  (E)", "pt": "Nova de Gelo  (E)"},
	"kit_swift_stab": {"en": "Swift Stab  (LMB)", "pt": "Estocada Veloz  (LMB)"},
	"kit_fan_knives": {"en": "Fan of Knives  (E)", "pt": "Leque de Lâminas  (E)"},
	"kit_cleave": {"en": "Cleave  (LMB)", "pt": "Cutilada  (LMB)"},
	"kit_whirlwind": {"en": "Whirlwind  (E)", "pt": "Redemoinho  (E)"},
	"kit_shadow_rend": {"en": "Shadow Rend  (Q)", "pt": "Rasgo Sombrio  (Q)"},
	"kit_dodge": {"en": "Dodge  (Shift)", "pt": "Esquiva  (Shift)"},
	"cp_kit_bolt_nums": {"en": "%d dmg · %.2f s cd · ranged umbral bolt · crit %d%%",
			"pt": "%d dano · %.2f s rec · seta umbral à distância · crít %d%%"},
	"cp_kit_nova_nums": {"en": "%d dmg · 5 s cd · 2.8 m radial · hard Chill",
			"pt": "%d dano · 5 s rec · 2,8 m radial · Gelidez forte"},
	"cp_kit_stab_nums": {"en": "%d dmg · %.2f s cd · 60 deg · 1.8 m · crit %d%%",
			"pt": "%d dano · %.2f s rec · 60° · 1,8 m · crít %d%%"},
	"cp_kit_fan_nums": {"en": "5 x %d dmg · 4.5 s cd · piercing steel fan",
			"pt": "5 x %d dano · 4,5 s rec · leque de aço perfurante"},
	"cp_kit_cleave_nums": {"en": "%d dmg · %.2f s cd · 110 deg · 2.2 m · crit %d%%",
			"pt": "%d dano · %.2f s rec · 110° · 2,2 m · crít %d%%"},
	"cp_kit_whirl_nums": {"en": "%d dmg · 4 s cd · full circle · 2.6 m + shove",
			"pt": "%d dano · 4 s rec · círculo completo · 2,6 m + empurrão"},
	"cp_kit_rend_nums": {"en": "%d dmg · 5 s cd · 130 deg · 2.2 m — umbral",
			"pt": "%d dano · 5 s rec · 130° · 2,2 m — umbral"},
	"cp_kit_dodge_nums": {"en": "4 m dash · 3 charges · %.2f s recharge — no i-frames",
			"pt": "4 m de investida · 3 cargas · %.2f s de recarga — sem invulnerabilidade"},
	"cp_locked": {"en": "   [locked]", "pt": "   [bloqueada]"},
	"cp_rend_stone_note": {"en": "Shadow Rend awakens with a Bestial Skill stone (the first pack drops one).",
			"pt": "Rasgo Sombrio desperta com uma Pedra de Perícia Bestial (a primeira alcateia derruba uma)."},
	"sock_cleave": {"en": "Cleave", "pt": "Cutilada"},
	"sock_rend": {"en": "Rend", "pt": "Rasgo"},
	"sock_dodge": {"en": "Dodge", "pt": "Esquiva"},
	"cp_socket_on": {"en": "— socket on %s —", "pt": "— encaixar em %s —"},
	"cp_socket_rune_chip": {"en": "◇ socket rune", "pt": "◇ encaixar runa"},
	"cp_remove_rune": {"en": "remove ◆ %s", "pt": "remover ◆ %s"},
	"cp_no_runes": {"en": "no runes in the bag — Elites drop them.",
			"pt": "sem runas na bolsa — Elites as derrubam."},
	"cp_runes_drop_note": {"en": "Runes drop from Elites — click a socket chip to slot one.",
			"pt": "Runas caem de Elites — clique num chip de encaixe para colocar uma."},

	# ---- character panel: pets / mounts ---------------------------------------------------------
	"cp_pets_header": {"en": "Pets — %d/%d bonded", "pt": "Pets — %d/%d vinculados"},
	"cp_pets_none": {"en": "none bonded — weaken a Gloamfen Stalker below 35% HP and press F with a Soul Snare (stalkers drop them)",
			"pt": "nenhum vinculado — enfraqueça um Gloamfen Stalker abaixo de 35% de HP e aperte F com um Laço de Alma (os stalkers os derrubam)"},
	"cp_resting": {"en": "· resting", "pt": "· descansando"},
	"cp_on_hunt": {"en": "· on the hunt", "pt": "· na caçada"},
	"cp_to_stables": {"en": "Stable", "pt": "→ estábulo"},
	"cp_pet_roll": {"en": "roll %d%%  ·  %s", "pt": "rolagem %d%%  ·  %s"},
	"cp_stables_header": {"en": "STABLES — %d resting", "pt": "ESTÁBULO — %d descansando"},
	"cp_stable_row": {"en": "%s\nroll %d%%  ·  %s", "pt": "%s\nrolagem %d%%  ·  %s"},
	"cp_make_active": {"en": "make active", "pt": "tornar ativo"},
	"cp_pack_full_tip": {"en": "active pack is full — stable one first",
			"pt": "a alcateia ativa está cheia — estabule um antes"},
	"cp_stables_note": {"en": "Overflow captures STABLE the oldest bond — pets are never abandoned and never die (they rest 15 s, and respawn with you).",
			"pt": "Capturas excedentes ESTABULAM o vínculo mais antigo — pets nunca são abandonados e nunca morrem (descansam 15 s e renascem com você)."},
	"cp_mounts_header": {"en": "Mounts — press Z on the hunt to ride",
			"pt": "Montarias — aperte Z na caçada para montar"},
	"cp_mounts_none": {"en": "none owned — the Haven VENDOR sells the Gloam Strider (walking); a FLYING drakeling is said to nest with the Emberwing Matriarch.",
			"pt": "nenhuma adquirida — o VENDEDOR do Refúgio vende o Gloam Strider (terrestre); dizem que um dracontino VOADOR aninha com a Matriarca Emberwing."},
	"cp_mount_row": {"en": "%s — %s · x%.1f speed%s", "pt": "%s — %s · x%.1f de velocidade%s"},
	"cp_flying": {"en": "FLYING", "pt": "VOADORA"},
	"cp_walking": {"en": "walking", "pt": "terrestre"},
	"cp_active_tag": {"en": "   Selected", "pt": "   ← ativa"},
	"cp_select": {"en": "select", "pt": "selecionar"},
	"cp_mounts_note": {"en": "Walking mounts respect terrain; FLYING mounts cross water and rock (land on solid ground). Attacking or taking damage dismounts you.",
			"pt": "Montarias terrestres respeitam o terreno; as VOADORAS cruzam água e rocha (pouse em chão firme). Atacar ou receber dano desmonta você."},

	# ---- hunt HUD / messages (main.gd) -----------------------------------------------------------
	"hud_stats": {"en": "Lv %d   Gold %d   Kills %d   Stones %d   Snares %d   Bag %d/%d   Pets %d/%d",
			"pt": "Nv %d   Ouro %d   Abates %d   Pedras %d   Laços %d   Bolsa %d/%d   Pets %d/%d"},
	"hud_hint_base": {"en": "LMB cleave · Shift dodge x3 · Q rend · E whirlwind · 1-4 skills · Z mount · F bond · C character · K keys · Esc haven",
			"pt": "LMB cutilada · Shift esquiva x3 · Q rasgo · E redemoinho · 1-4 habilidades · Z montaria · F vínculo · C personagem · K teclas · Esc refúgio"},
	"hud_hint_rend": {"en": " · Q shadow rend", "pt": " · Q rasgo sombrio"},
	"hud_hint_bosses": {"en": " — hunt the Fenwitch Hag, the Legendary duo, the Matriarch",
			"pt": " — cace a Fenwitch Hag, a dupla Lendária, a Matriarca"},
	"hud_hint_leg": {"en": " · a LEGENDARY prowls: %s", "pt": " · uma LENDÁRIA ronda: %s"},
	"hud_resting": {"en": "  · resting", "pt": "  · descansando"},
	"msg_no_snare": {"en": "no Soul Snare — stalkers drop them",
			"pt": "sem Laço de Alma — stalkers os derrubam"},
	"msg_no_stalker": {"en": "no stalker within 3 m", "pt": "nenhum stalker a até 3 m"},
	"msg_too_strong": {"en": "too strong — wound it below 35%",
			"pt": "forte demais — fira-o abaixo de 35%"},
	"msg_slots_full": {"en": "pet slots full — F again in 3 s stables %s",
			"pt": "slots de pet cheios — F de novo em 3 s estabula %s"},
	"msg_sent_stables": {"en": "%s sent to the stables", "pt": "%s foi para o estábulo"},
	"msg_bonded": {"en": "BONDED — %s (pet %d/%d)", "pt": "VINCULADO — %s (pet %d/%d)"},
	"msg_resisted": {"en": "RESISTED!", "pt": "RESISTIU!"},
	"msg_matriarch_felled": {"en": "MATRIARCH FELLED!", "pt": "A MATRIARCA CAIU!"},
	"msg_mount_bonded": {"en": "MOUNT BONDED — Emberwing Drakeling (press Z to FLY)",
			"pt": "MONTARIA VINCULADA — Emberwing Drakeling (aperte Z para VOAR)"},
	"msg_victory_matriarch": {"en": "Victory — the Emberfang Blade is yours. Forge/enchant/sell at the Haven (Esc).",
			"pt": "Vitória — a Emberfang Blade é sua. Forje/encante/venda no Refúgio (Esc)."},
	"msg_fenwitch": {"en": "THE FENWITCH FALLS!", "pt": "A FENWITCH CAI!"},
	"msg_one_falls": {"en": "ONE FALLS — the other AVENGES!", "pt": "UM CAI — o outro se VINGA!"},
	"msg_duo_hint": {"en": "Half the duo is down — the survivor is enraged. Finish it.",
			"pt": "Metade da dupla caiu — o sobrevivente está enfurecido. Acabe com ele."},
	"msg_duo_falls": {"en": "THE LEGENDARY DUO FALLS!", "pt": "A DUPLA LENDÁRIA CAI!"},
	"msg_victory_duo": {"en": "Victory — Legendary spoils twice over. Forge/enchant/sell at the Haven (Esc).",
			"pt": "Vitória — espólios Lendários em dobro. Forje/encante/venda no Refúgio (Esc)."},
	"msg_snare_shower": {"en": "SOUL SNARE SHOWER!", "pt": "CHUVA DE LAÇOS DE ALMA!"},
	"msg_leg_falls": {"en": "%s FALLS!", "pt": "%s CAI!"},
	"msg_victory_leg": {"en": "The hunt's Legendary falls — rare spoils are yours. Forge/enchant/sell at the Haven (Esc).",
			"pt": "A Lendária da caçada cai — espólios raros são seus. Forje/encante/venda no Refúgio (Esc)."},
	"msg_level_up": {"en": "LEVEL %d!", "pt": "NÍVEL %d!"},
	"msg_level_points": {"en": "+%d attribute points · +%d skill point (C)",
			"pt": "+%d pontos de atributo · +%d ponto de habilidade (C)"},
	"msg_gold": {"en": "+%d gold", "pt": "+%d de ouro"},
	"msg_stone": {"en": "Bestial Skill stone!", "pt": "Pedra de Perícia Bestial!"},
	"msg_rend_awake": {"en": "SHADOW REND awakened — press Q",
			"pt": "RASGO SOMBRIO desperto — aperte Q"},
	"msg_snare": {"en": "Soul Snare!", "pt": "Laço de Alma!"},
	"msg_equipped": {"en": "%s — equipped", "pt": "%s — equipado"},
	"msg_rune_drop": {"en": "a RUNE — socket it on a skill (C - Skills)",
			"pt": "uma RUNA — encaixe numa habilidade (C - Habilidades)"},
	"msg_died": {"en": "You died — %d gold lost to the dark. Respawning...",
			"pt": "Você morreu — %d de ouro perdido para a escuridão. Renascendo..."},
	"confirm_return": {"en": "Return to Haven?", "pt": "Voltar ao Refúgio?"},
	"confirm_yes": {"en": "Yes", "pt": "Sim"},
	"confirm_no": {"en": "No", "pt": "Não"},
	"legendary_suffix": {"en": "%s — Legendary", "pt": "%s — Lendária"},
	"duo_label": {"en": "%s + %s — Legendary Duo", "pt": "%s + %s — Dupla Lendária"},

	# ---- keybind card (main.gd) --------------------------------------------------------------------
	"kb_title": {"en": "KEYBINDS", "pt": "TECLAS"},
	"kb_move_k": {"en": "WASD / arrows", "pt": "WASD / setas"},
	"kb_move_v": {"en": "move", "pt": "mover"},
	"kb_aim_k": {"en": "mouse", "pt": "mouse"},
	"kb_aim_v": {"en": "aim", "pt": "mirar"},
	"kb_atk_k": {"en": "LMB / Space", "pt": "LMB / Espaço"},
	"kb_atk_v": {"en": "cleave", "pt": "cutilada"},
	"kb_dodge_k": {"en": "Shift / RMB", "pt": "Shift / RMB"},
	"kb_dodge_v": {"en": "dodge (3 charges)", "pt": "esquiva (3 cargas)"},
	"kb_q_v": {"en": "Shadow Rend (stone)", "pt": "Rasgo Sombrio (pedra)"},
	"kb_e_v": {"en": "Whirlwind", "pt": "Redemoinho"},
	"kb_slots_v": {"en": "class skills (learn: C - Skills)",
			"pt": "habilidades de classe (C)"},
	"kb_f_v": {"en": "bond pet (Soul Snare)", "pt": "vincular pet (Laço de Alma)"},
	"kb_z_v": {"en": "mount / dismount", "pt": "montar / desmontar"},
	"kb_c_v": {"en": "character panel", "pt": "painel do personagem"},
	"kb_k_v": {"en": "this card", "pt": "este cartão"},
	"kb_esc_v": {"en": "return to Haven", "pt": "voltar ao Refúgio"},
}

# Fixed chrome string for the current language. Missing keys fall back to the
# key's EN entry, then to the key itself — never crashes on a typo.
static func t(key: String) -> String:
	_ensure()
	var e: Dictionary = S.get(key, {})
	if e.is_empty():
		return key
	return str(e.get(lang, e.get("en", key)))

# Data-driven text: "<field>_pt" wins when the language is pt and the field
# exists; otherwise the EN field (skill_trees.json nodes/branches/statuses).
static func pick(d: Dictionary, field: String, default := "") -> String:
	_ensure()
	if lang == "pt" and d.has(field + "_pt"):
		return str(d[field + "_pt"])
	return str(d.get(field, default))

# Registry-word lookup ("rarity"+"rare" -> t("rarity_rare")); unknown words
# pass through untouched so data never renders as a bare key.
static func term(prefix: String, word: String) -> String:
	var key := prefix + "_" + word
	if S.has(key):
		return t(key)
	return word

static func set_lang(l: String) -> void:
	_ensure()
	lang = "pt" if l == "pt" else "en"
	# MERGE into the shared settings file — display (ProtoDisplay) and audio
	# (ProtoAudio) keys live here too; this used to rewrite it as {"lang"} alone
	# and silently wiped them on every language toggle
	var root := {}
	var raw := FileAccess.get_file_as_string(SETTINGS_PATH)
	if not raw.is_empty():
		var parsed: Variant = JSON.parse_string(raw)
		if parsed is Dictionary:
			root = parsed
	root["lang"] = lang
	var f := FileAccess.open(SETTINGS_PATH, FileAccess.WRITE)
	if f != null:
		f.store_string(JSON.stringify(root, "\t"))

# Lazy load on first access; a missing/corrupt settings file just keeps "en".
static func _ensure() -> void:
	if _loaded:
		return
	_loaded = true
	var raw := FileAccess.get_file_as_string(SETTINGS_PATH)
	if raw.is_empty():
		return
	var parsed: Variant = JSON.parse_string(raw)
	if parsed is Dictionary and str((parsed as Dictionary).get("lang", "")) in ["en", "pt"]:
		lang = str((parsed as Dictionary)["lang"])
