#!/usr/bin/env bash
# Dragon Heroes terminal theme — the shared look for every tool that talks to a
# human (Ricardo, 2026-09-13: "i want to keep track of it and have it
# beautifully exhibited and themed in the terminal").
#
#   source "$(dirname "$0")/dh_term.sh"
#   dh_banner "TRAINING FORGE" "isolated, cumulative runs"
#   dh_rule "fen_boar"; dh_kv run "$RUN"; dh_ok "gate passed"
#
# Palette = the arena console's (game/arena/console.gd): ember #ff9a3c, pale
# #d9d4c7, dim, cyan #7fd8ff, green, red. Colour is truecolor and is dropped
# whenever stdout is not a terminal, TERM is dumb, or NO_COLOR is set — so a
# tee'd log file stays plain text and greppable.
#
# The dragon is tools/art/dragon.txt, generated by tools/art/make_dragon.py.

DH_TOOLS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -t 1 ] && [ -z "${NO_COLOR:-}" ] && [ "${TERM:-dumb}" != "dumb" ]; then
  C_EMBER=$'\033[38;2;255;154;60m'; C_PALE=$'\033[38;2;217;212;199m'
  C_DIM=$'\033[38;2;128;125;115m';  C_CYAN=$'\033[38;2;127;216;255m'
  C_GREEN=$'\033[38;2;126;217;87m'; C_RED=$'\033[38;2;231;76;60m'
  C_GOLD=$'\033[38;2;255;214;148m'; C_B=$'\033[1m'; C_0=$'\033[0m'
else
  C_EMBER=""; C_PALE=""; C_DIM=""; C_CYAN=""; C_GREEN=""; C_RED=""
  C_GOLD=""; C_B=""; C_0=""
fi

dh_cols() {                    # terminal width, clamped to something printable
  local c="${COLUMNS:-0}"
  [ "$c" -gt 0 ] 2>/dev/null || c="$(tput cols 2>/dev/null || echo 80)"
  [ "$c" -ge 60 ] || c=60
  [ "$c" -le 100 ] && echo "$c" || echo 100
}

dh_repeat() { local n=$1 s=$2 o=""; while [ "$n" -gt 0 ]; do o="$o$s"; n=$((n-1)); done; printf '%s' "$o"; }

dh_rule() {                    # dh_rule [LABEL] — an ember rule with a title
  local w; w=$(dh_cols)
  if [ $# -eq 0 ]; then
    printf '%s%s%s\n' "$C_EMBER" "$(dh_repeat "$w" '─')" "$C_0"
  else
    local label=" $* " len=$(( ${#1} + 2 ))
    len=$(( ${#label} ))
    printf '%s──%s%s%s%s%s%s\n' "$C_EMBER" "$C_0" "$C_B$C_GOLD" "$label" "$C_0" \
      "$C_EMBER" "$(dh_repeat $(( w - len - 2 > 0 ? w - len - 2 : 0 )) '─')$C_0"
  fi
}

dh_art() {                     # the dragon, tinted as a vertical ember gradient
  local art="$DH_TOOLS/art/dragon.txt"
  [ -f "$art" ] || return 0
  if [ -z "$C_EMBER" ]; then cat "$art"; return 0; fi
  awk -v n="$(wc -l < "$art")" '
    BEGIN { split("255,214,148 255,178,92 255,154,60 232,118,40 198,86,28 158,60,20 120,42,14 92,32,12", p, " ") }
    { i = int((NR - 1) / n * 8) + 1; if (i > 8) i = 8; split(p[i], c, ",");
      printf "\033[38;2;%s;%s;%sm%s\033[0m\n", c[1], c[2], c[3], $0 }' "$art"
}

dh_banner() {                  # dh_banner [TITLE] [SUBTITLE]
  local title="${1:-DRAGON HEROES}" sub="${2:-}"
  printf '\n'
  dh_art
  printf '\n  %s%s%s\n' "$C_B$C_GOLD" "$(echo "$title" | sed 's/./& /g')" "$C_0"
  [ -z "$sub" ] || printf '  %s%s%s\n' "$C_DIM" "$sub" "$C_0"
  printf '\n'
}

dh_kv()   { printf '  %s%-14s%s %s\n' "$C_DIM" "$1" "$C_0" "${*:2}"; }
dh_say()  { printf '%s  ·%s %s\n' "$C_EMBER" "$C_0" "$*"; }
dh_ok()   { printf '%s  ✓%s %s\n' "$C_GREEN" "$C_0" "$*"; }
dh_warn() { printf '%s  !%s %s\n' "$C_EMBER" "$C_0" "$*"; }
dh_err()  { printf '%s  ✗%s %s\n' "$C_RED" "$C_0" "$*"; }

dh_bar() {                     # dh_bar DONE TOTAL [WIDTH] — a filled ember bar
  local done=$1 total=$2 w=${3:-24} f
  [ "$total" -gt 0 ] 2>/dev/null || total=1
  f=$(( done * w / total )); [ "$f" -le "$w" ] || f=$w; [ "$f" -ge 0 ] || f=0
  printf '%s%s%s%s%s' "$C_EMBER" "$(dh_repeat "$f" '█')" "$C_DIM" \
    "$(dh_repeat $(( w - f )) '░')" "$C_0"
}
