#!/usr/bin/env python3
"""Compile the reviewed authoring data into C++ tables and a Godot display pack."""
import hashlib
import json
from pathlib import Path
import shutil
import sys
import jsonschema
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from genforge.living.build import build, canonical, mask
from genforge.living.validation import load_validated, TAGS, STATUSES


def load_config(path=None):
    def invalid_constant(value):
        raise ValueError(f"Non-finite preview number: {value}")
    config = json.loads((path or ROOT / "genforge/playable/fen_bells.json").read_text(), parse_constant=invalid_constant)
    try:
        jsonschema.validate(config, json.loads((ROOT / "content/schemas/living-preview.schema.json").read_text()))
    except jsonschema.ValidationError as error:
        raise ValueError(f"Playable configuration: {error.message}") from error
    release = load_validated(ROOT / config["release"])
    creature = next((c for c in release["creatures"] if c["id"] == config["creature"]), None)
    if creature is None:
        raise ValueError("Playable creature reference does not exist")
    if [p["skill"] for p in config["phases"]] != creature["skills"]:
        raise ValueError("Playable phase order must implement the complete authored creature kit")
    effects = sorted(release["effects"], key=lambda r: r["id"])
    if len(effects) > 8 or len(release["artifacts"]) != 4:
        raise ValueError("Preview v1 supports up to eight effects and four artifact presets")
    if any(e["action"] not in ("echo", "chain", "resource", "ward") for e in effects):
        raise ValueError("Preview host does not implement one of the authored effect actions")
    root_tags = {"hit": ({"melee"}, {"storm"}), "dodge": ({"dodge"},), "pet_hit": ({"pet"},)}
    for effect in effects:
        if not any(set(effect["tags"]) <= tags for tags in root_tags.get(effect["trigger"], ())):
            raise ValueError("Preview host cannot supply an authored effect trigger/tag combination")
        if not set(effect["requires"]) <= {"wet"} or (effect["trigger"] == "dodge" and effect["requires"]):
            raise ValueError("Preview host cannot supply an authored effect status condition")
        if effect["action"] in ("echo", "chain") and effect["trigger"] == "dodge":
            raise ValueError("Preview dodge event has no enemy target for this effect")
        if effect["action"] != "chain" and effect["max_targets"] != 1:
            raise ValueError("Preview non-chain effects require exactly one target")
    return config, release, creature, effects


def stage():
    config, release, creature, effects = load_config()
    review = build(ROOT / config["release"], ROOT / "genforge/candidates/living")
    output = ROOT / "game/living/generated"
    output.mkdir(parents=True, exist_ok=True)
    art = creature["art"].split(".")[-1]
    for name in ("albedo.png", "emissive.png", "atlas.json"):
        shutil.copyfile(review / "art" / art / name, output / name)
    texture_bytes = 0
    for texture in (output/"albedo.png", output/"emissive.png", ROOT/"game/living/shrine.png",
                    ROOT/"game/prototype/art/hero/sheet.png", ROOT/"game/prototype/art/gloamfen_wisp/sheet.png"):
        with Image.open(texture) as image:
            texture_bytes += image.width*image.height*4
    if texture_bytes > 8*1024*1024:
        raise ValueError("Playable trial exceeds the 8 MiB decoded texture budget")
    content_hash = json.loads((review / "manifest.json").read_text())["content_hash"]
    # Simulation parity is independent of PNG encoder/Pillow versions.
    stamp = int(hashlib.sha256(canonical({"config": config, "release": release})).hexdigest()[:8],16)
    (output / "chapter.json").write_bytes(canonical({"release": release, "playable": config,
        "content_hash": content_hash, "simulation_stamp": stamp, "decoded_texture_bytes": texture_bytes}))
    lines = ["// Generated by tools/stage_living_preview.py; edit the authoring JSON.",
             "#pragma once", "#include <array>", "#include <dh/sim/effects.hpp>",
             "namespace dh::sim::living_data {",
             f"inline constexpr unsigned simulation_stamp = {stamp}u;",
             "struct Phase { unsigned verb, windup, recovery; float damage, radius; };",
             f"inline constexpr std::array<EffectDef,{len(effects)}> effects = {{{{"]
    for e in effects:
        lines.append("{EffectTrigger::%s,%d,%d,%d,EffectAction::%s,%d,%d,%d,%d}," % (
            e["trigger"], mask(e["tags"], TAGS), mask(e["requires"], STATUSES),
            mask(e["consumes"], STATUSES), e["action"], e["magnitude_permille"],
            e["cooldown_ticks"], e["max_targets"], e["budget"]))
    lines.append("}};")
    lines.append("inline constexpr std::array<unsigned,%d> visual_ticks = {%s};" % (len(effects), ",".join(
        str(max(1,round(sum(e["vfx"][key] for key in ("anticipation_ms","impact_ms","dissipate_ms"))*30/1000))) for e in effects)))
    ids = [e["id"] for e in effects]
    artifacts = sorted(release["artifacts"], key=lambda a: ["legendary", "relic", "mythic", "divine"].index(a["rarity"]))
    lines.append("inline constexpr std::array<unsigned,4> artifact_masks = {" + ",".join(
        str(sum(1 << ids.index(e) for e in a["effects"])) for a in artifacts) + "};")
    lines.append("inline constexpr std::array<float,4> affixes = {" + ",".join(
        f"{a['affix_budget']}.0f" for a in artifacts) + "};")
    lines.append(f"inline constexpr std::array<Phase,{len(config['phases'])}> phases = {{{{")
    for p in config["phases"]:
        verb = ["pools", "storm", "leap", "sweep", "ward"].index(p["verb"])
        lines.append("{%d,%d,%d,%.6ff,%.6ff}," % (verb,p["windup"],p["recovery"],p["damage"],p["radius"]))
    lines.append("}};")
    for key in ("hunter_hp", "boss_hp", "move_speed", "base_damage", "affix_damage_per_point"):
        lines.append(f"inline constexpr float {key} = {float(config[key]):.6f}f;")
    lines.append("} // namespace dh::sim::living_data\n")
    (ROOT / "sim/libs/dh-sim/include/dh/sim/living_content.generated.hpp").write_text("\n".join(lines))
    print(f"PLAYABLE CONTENT OK: {creature['name']}, {len(config['phases'])} phases, 4 artifacts; {review}")
    return review


if __name__ == "__main__":
    stage()
